### ISSUE TITLE
google-auth doc

### ISSUE THREAD

**Issue by xmedeko** [GoogleCloudPlatform/httplib2shim#10]
For the google-auth and the new google-api-python-client (google-api-python-client==1.6.4, google-auth==1.2.1, google-auth-httplib2==0.0.3) I use:
```python
credentials = google.auth.default()
http = httplib2shim.Http()
http = google_auth_httplib2.AuthorizedHttp(credentials, http=http)
```
Is that ok? Please document it, thanks.

**Comment by theacodes** [comment]
Yep, that's fine. Happy to accept a PR to add it to this projects README.
