### ISSUE TITLE
proxy_info cannot be None for the ver. 0.0.2

### ISSUE THREAD

**Issue by xmedeko** [GoogleCloudPlatform/httplib2shim#8]
After upgrade to ver. 0.0.2 I cannot call `httplib2shim.Http(proxy_info=None)`, it results in:
```
 File "/usr/local/lib/python3.5/dist-packages/httplib2shim/__init__.py", line 114, in __init__
    pool = self._make_pool(proxy_info=proxy_info())
TypeError: 'NoneType' object is not callable
```
Also, the `proxy_info` for the httplib2 may not be callable. While it's easy to make a lambda to change variable to callable, it's nice to allow `None` as proxy_info (and backward compatible, too.)

**Comment by theacodes** [comment]
@xmedeko do you want to make a PR to implement the behavior you're expecting?
